#!/usr/bin/env node
/**
 * calibrate_ai_signals.js — build ai_signal_blocklist.json from the vendored
 * AI-vocabulary lists, RE-TIERED against our own human reference corpus.
 *
 * Generic AI word-lists (Wikipedia, brandonwise/humanizer, the LinkedIn skill)
 * over-flag: they ban "landscape", "embark", "crucial", "at the end of the day"
 * — all of which Juan Magallanes uses in his real advisory replies. Hard-failing
 * on those would reject authentic human writing. So we measure every candidate
 * against the 189k-word Juan corpus and keep in the HARD-FAIL tier only terms
 * with near-zero human use (<= HARD_MAX per 1k words). Everything a human
 * actually says drops to the advisory tier.
 *
 * This is exactly what the monthly updater does with newly-scraped Wikipedia
 * terms — so the auto-update can never introduce a term that breaks the voice.
 *
 *   node calibrate_ai_signals.js   # regenerates ai_signal_blocklist.json
 */
const fs = require('fs');
const path = require('path');

const HARD_MAX = 0.02;   // per-1k-words in the human corpus; <= this = a true tell

const vocab = require('./vendor_humanizer_vocabulary.js');
const CORPUS_DIR = path.join(__dirname, '..', '..', 'context-pack', 'brand-voice', 'juan-magallanes-source');

let corpus = '';
for (const f of fs.readdirSync(CORPUS_DIR)) corpus += '\n' + fs.readFileSync(path.join(CORPUS_DIR, f), 'utf8');
const low = corpus.toLowerCase();
const wc = corpus.split(/\s+/).filter(Boolean).length;

function per1k(term) {
  const re = new RegExp(`\\b${term.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\b`, 'gi');
  return ((low.match(re) || []).length / wc) * 1000;
}
function phrasePer1k(p) { // literal substring density
  let n = 0, i = 0; const t = p.toLowerCase();
  while ((i = low.indexOf(t, i)) !== -1) { n++; i += t.length; }
  return (n / wc) * 1000;
}

// A word is a HARD tell only if BOTH signals agree: intrinsically suspicious
// (brandonwise Tier-1 or Tier-2 — a "dead giveaway" or "suspicious-when-clustered")
// AND rare in our human corpus (<= HARD_MAX/1k). Tier-3 words are common English
// (key, significant, essential, valuable) — always advisory, never a hard fail.
const suspicious = new Set([...vocab.TIER_1, ...vocab.TIER_2]);
const allWords = [...new Set([...vocab.TIER_1, ...vocab.TIER_2, ...vocab.TIER_3])];
const tier_a_words = [], tier_b_words = [];
for (const w of allWords) {
  if (/[^a-z\- ]/i.test(w)) continue;               // skip odd tokens
  const hard = suspicious.has(w) && per1k(w) <= HARD_MAX;
  (hard ? tier_a_words : tier_b_words).push(w);
}

// literal phrases we can string-match (skip regex-object AI_PHRASES here; those
// stay as coded detectors in ai_signals.js). Pull the plain ones we seeded.
const seedPhrases = [
  'treasure trove', 'rich tapestry', 'a rich tapestry', 'rich history', 'hidden gem',
  'moreover', 'furthermore', 'in essence', 'it is important to note', 'it is worth mentioning',
  'it is worth noting', 'as mentioned earlier', 'needless to say', 'there is no one-size-fits-all',
  'one-size-fits-all solution', 'a complex and multifaceted issue', 'it is crucial to consider',
  'plays a crucial role', 'plays a significant role', 'plays a vital role', 'plays a key role',
  'it is important to remember', 'in conclusion', 'to summarize', 'in summary',
  'stands as a testament', 'a testament to', 'serves as a testament', 'in the world of',
  'in the realm of', 'navigating the complexities', 'the importance of', 'the power of',
  'a wide range of', 'a variety of', 'when it comes to', 'at the end of the day', 'all in all',
  'that being said', 'additionally', 'let’s dive in', 'deep dive', 'game changer',
  'game-changer', 'move the needle', 'in today’s fast-paced world', 'pave the way',
];
const tier_a_phrases = [], tier_b_phrases = [];
for (const p of [...new Set(seedPhrases)]) {
  (phrasePer1k(p) <= HARD_MAX ? tier_a_phrases : tier_b_phrases).push(p);
}

const out = {
  _README: 'Auto-generated by calibrate_ai_signals.js. TIER-A = hard-fail (<= ' + HARD_MAX +
    '/1k in the Juan human corpus); TIER-B = advisory only (human uses them). Do not hand-edit — ' +
    're-run the calibrator. The monthly updater appends new Wikipedia/arXiv candidates through the ' +
    'same corpus filter so it can never promote a word that rejects the authentic voice.',
  _sources: [
    'vendor_humanizer_vocabulary.js (brandonwise/humanizer: Wikipedia:Signs of AI writing + arXiv 2503.01659 + observed ChatGPT/Claude/Gemini/Llama)',
    'https://en.wikipedia.org/wiki/Wikipedia:Signs_of_AI_writing',
    'https://arxiv.org/abs/2301.11305 (DetectGPT — burstiness / curvature)',
    'https://arxiv.org/abs/2503.01659 (stylistic fingerprints survive tone-prompting)',
    'LinkedIn humanizer skill (Flesch>55, sentence-variance>40%, per-100w density)',
  ],
  _baseline_corpus: 'context-pack/brand-voice/juan-magallanes-source',
  _baseline_words: wc,
  _hard_max_per_1k: HARD_MAX,
  tier_a_words: tier_a_words.sort(),
  tier_a_phrases: tier_a_phrases.sort(),
  tier_b_words: tier_b_words.sort(),
  tier_b_phrases: tier_b_phrases.sort(),
};
fs.writeFileSync(path.join(__dirname, 'ai_signal_blocklist.json'), JSON.stringify(out, null, 2) + '\n');
console.log(`corpus ${wc} words`);
console.log(`TIER-A words:   ${tier_a_words.length}  (hard-fail)`);
console.log(`TIER-B words:   ${tier_b_words.length}  (advisory — human uses them)`);
console.log(`TIER-A phrases: ${tier_a_phrases.length}`);
console.log(`TIER-B phrases: ${tier_b_phrases.length}  -> ${tier_b_phrases.join(', ')}`);
